# Generated by Django 4.1.5 on 2023-01-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_id', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('time_autorization', models.FloatField(default=0.0)),
                ('cash_account', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
