# Generated by Django 4.1.5 on 2023-01-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Treiner_warker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport.clients')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport.product')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_treiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=20)),
                ('time_training', models.CharField(max_length=20)),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport.clients')),
                ('treiner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport.treiner_warker')),
            ],
        ),
    ]
